[GLOBAL]
dynamic_ui = false
colors = true

remote_cache_read = false
remote_cache_write = false

[pytest]
args = ["-vv", "--no-header"]

[test]
use_coverage = true

[coverage-py]
report = ["xml", "html", "console"]