[GLOBAL]
pants_version = "2.12.1rc2"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.bandit",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.pylint",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.docker",
  "pants.backend.docker.lint.hadolint",
]

[python]
interpreter_constraints = ["CPython==3.10.*"]
enable_resolves = true

[python.resolves]
python-default = "lock.txt"

[mypy]
version = "mypy==0.971"
lockfile = "mypy_lockfile.txt"

[docker]
build_args = ["GIT_COMMIT"]

[docker.registries.github]
address = "ghcr.io/fucina"
default = true

[anonymous-telemetry]
enabled = true
repo_id = "eb7c7d00-686b-4616-b5d2-566548ffcdf8"
