plugins = [
    "treb.plugins.docker"
]

[state]
repo_path = "../"
push = false

[project]
repo_path = "./state/"

[vars]
gh_repo = "ghcr.io/fucina"
gcp_repo = "europe-west2-docker.pkg.dev/<project-id>/fucina"
gcp_project = "<project-id>"
